fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: [ json ], fallback_format: json, prefer_extension: true }
    param_fetcher_listener: true
    view:
        view_response_listener: true
        formats:
            json: true
    zone:
        - { path: ^/Api/* }
